BODP-5626: Ability to view seasonal services count. Timetables
department-for-transport-BODS/bods pull request #129
Opened 2023-01-13 15:03 UTC by AndreaIto

In the Timetable data review page, as an operator, added new Sesonal Service in the blue banner.  Added new link: `Manage', this link should be taken to the seasonal service set up page, today: to the placeholder page.

![Screenshot 2023-01-13 at 15 02 57](https://user-images.githubusercontent.com/111745616/212351622-de11aac7-90b5-4637-be69-3d9f77a4380b.png)

![Screenshot 2023-01-13 at 15 03 13](https://user-images.githubusercontent.com/111745616/212351628-22c072f6-1f3a-4d4c-9576-3ff0bb28f25b.png)

@ITO-PaulHolland @anguskbell @marcusher-ito

2023-01-18 12:58 UTC, AndreaIto commented
![Screenshot 2023-01-18 at 12 52 58](https://user-images.githubusercontent.com/111745616/213177695-2047f507-9832-49b8-8d9c-913040684600.png)

2023-01-23 10:31 UTC, anguskbell commented on transit_odp/organisation/querysets.py
> +    def get_seasonal_service_counter(self, org_id: int) -> int:
This isn't a very descriptive name for a method on the `SeasonalService` queryset. Better would be something like `get_count_in_organisation`.

2023-01-23 13:48 UTC, anguskbell requested changes
If you rename the queryset method, then I'll approve.

2023-01-23 13:52 UTC, AndreaIto commented on transit_odp/organisation/querysets.py
> +    def get_count_in_organisation(self, org_id: int) -> int:
I renamed the method as you request `get_count_in_organisation`
@anguskbell

2023-01-25 14:35 UTC, anguskbell submitted a review, later dismissed

2023-01-25 16:26 UTC, anguskbell approved these changes
If you rename the queryset method, then I'll approve.

2023-01-25 16:27 UTC, merged