changes to reorder LTA extract data columns and add columns
department-for-transport-BODS/bods pull request #535
Opened 2023-10-19 13:31 UTC by alvak1

Overview of changes
- Re-order columns as per attachment
- Staleness status update
- fixes for failing test cases in browse app

2023-10-20 09:52 UTC, ndemenezes requested changes

2023-10-20 09:52 UTC, ndemenezes commented on transit_odp/browse/views/local_authority.py
> +from collections import OrderedDict
Remove unused import

2023-10-25 09:54 UTC, ndemenezes submitted a review, later dismissed

2023-10-25 10:11 UTC, pritish-ranjan01 approved these changes

2023-10-25 10:11 UTC, merged