story/BODS-68: Test cases for FareFrame tariffs.Tariff
department-for-transport-BODS/bods pull request #61
Opened 2022-11-23 16:34 UTC by ndemenezes

2022-11-23 16:58 UTC, surabhika requested changes

2022-11-23 16:58 UTC, surabhika commented on transit_odp/fares_validator/views/functions.py
> +        tariff = tariffs[0]
[1] This will break if "Tariff" is not present

2022-11-23 16:58 UTC, surabhika commented on transit_odp/fares_validator/views/functions.py
> +        tariff = tariffs[0]
[1]

2022-11-23 16:58 UTC, surabhika commented on transit_odp/fares_validator/views/functions.py
> +        tariff = tariffs[0]
[1]

2022-11-23 16:58 UTC, surabhika commented on transit_odp/fares_validator/views/functions.py
> +        tariff = tariffs[0]
[1]

2022-11-24 12:26 UTC, pritish-ranjan01 approved these changes

2022-11-24 12:30 UTC, merged