Hotfix/bods 4435
department-for-transport-BODS/bods pull request #947
Opened 2024-04-16 06:27 UTC by amitkpmguk

2024-04-16 06:35 UTC, brahmaduttau approved these changes

2024-04-16 09:12 UTC, PCridKPMG requested changes
Additional unit test for the false scenario?

2024-04-16 09:12 UTC, PCridKPMG commented on transit_odp/organisation/tests/csv/test_consumer_feedback.py
@amitkpmguk Can we add a unit test for a the add columns false check to ensure we test the various routes, unless I'm missing something

2024-04-16 09:23 UTC, amitkpmguk commented on transit_odp/organisation/tests/csv/test_consumer_feedback.py
Added the new test case for testing report without the columns, missed it earlier

2024-04-16 15:38 UTC, PCridKPMG submitted a review, later dismissed

2024-04-17 10:09 UTC, PCridKPMG approved these changes

2024-04-17 10:11 UTC, merged